Script started on Tue 31 Mar 2020 12:39:14 PM CDT
]0;grdirkso@turing: ~/HW4grdirkso@turing:~/HW4$ exitjava -cp .:mysql-connector-java-5.1.40-bin.jar HW4
Select and option from the menu below
1) Find all agents and clients in a given city
2) Add a new client, then purchase an available policy from a particular client
3) List all policies sold by a particular agent
4) Cancel  a policy
5) Add a new agent
6) Quit
1
Option 1: Find all agents and clients in a given city.
What city would you like to search? london
We will search for agents and clients in london.
Clients in london:
Agents in london:
5
Option 5: add a new agent for a city.
What city are you adding an agent for? 
sam   london
What is the agent's id (A_ID starts with 2)? 210
What is the agent's name (A_NAME)? sam
What is the agent's city (A_CITY)? london
What is the agent's zip (A_ZIP)? 9989
Updated Agents table:
201,  ANDREW,  DALLAS,  43214
202,  PHILIP,  PHOENIX,  85011
203,  JERRY,  BOSTON,  83125
204,  BRYAN,  ROGERS,  78291
205,  TOMMY,  DALLAS,  43214
206,  BRANT,  FAYETTEVILLE,  72701
207,  SMITH,  ROGERS,  78291
210,  sam,  london,  9989
212,  AMY,  ROGERS,  72756
213,  APRIL,  COLUMBUS,  31820
214,  MAIA,  CENTERTON,  72719
215,  LANDON,  BENTONVILLE,  72701
217,  EMILY,  TORONTO,  8976
218,  frank,  springdale,  8976
220,  Triston,  Fayetteville,  72701
315,  CAROLINE,  FAYETTEVILLE,  72703
1
Option 1: Find all agents and clients in a given city.
What city would you like to search? LONDON
We will search for agents and clients in LONDON.
Clients in LONDON:
Agents in LONDON:
210,  sam,  london,  9989
2
Option 2: Add a new client, then purchase an available policy from a particular agent.
Enter client’s name
CAMRYN
Enter client's city
PORTAGW E
Enter client’s zip
8765
We will add CAMRYN to our database as a client.
What type of policy would you like to purchase?
LIFE
There is not an agent in client's city
2
Option 2: Add a new client, then purchase an available policy from a particular agent.
Enter client’s name
CAMRYN
Enter client's city
LONDON
Enter client’s zip
8765
We will add CAMRYN to our database as a client.
What type of policy would you like to purchase?
CAR
Policy type not found
2
Option 2: Add a new client, then purchase an available policy from a particular agent.
Enter client’s name
CAMRYN
Enter client's city
LONDON
Enter client’s zip
87657
We will add CAMRYN to our database as a client.
What type of policy would you like to purchase?
LIFE
Policy type found. Here are the agents in LONDON
210,  sam,  london,  9989
These are all the available policies
302,  GOLD,  LIFE,  8
Provide the id of the Agent that you wish to purchase the policy from
210
Provide the policy id you want to purchase
302
Please provide the amount of the policy
5400
3
Option 3: List all policies sold by a particular agent
Please Provide the agent's name
TAN
Please provide the city the agent is in
FLORIDA
Either that Agent doesn't exist, or they are not in the city provided
3
Option 3: List all policies sold by a particular agent
Please Provide the agent's name
SAM
Please provide the city the agent is in
LONDON
GOLD,  LIFE,  8
4
Option 4: cancel a policy.
Policies sold:
401,  204,  106,  303,  2020-01-02,  2000.00
402,  201,  105,  305,  2019-08-11,  1500.00
403,  203,  106,  301,  2019-09-08,  3000.00
404,  207,  101,  305,  2019-06-21,  1500.00
405,  203,  104,  302,  2019-11-14,  4500.00
407,  205,  103,  304,  2020-10-15,  5000.00
408,  204,  103,  304,  2020-02-15,  5000.00
410,  202,  103,  303,  2020-01-30,  2000.00
411,  315,  128,  302,  2020-03-26,  3000.00
412,  218,  138,  301,  2020-03-31,  4500.00
413,  210,  141,  302,  2020-03-31,  5400.00
Enter the PURCHASE_ID of the policy to cancel: 
422
Updated POLICIES_SOLD table
401,  204,  106,  303,  2020-01-02,  2000.00
402,  201,  105,  305,  2019-08-11,  1500.00
403,  203,  106,  301,  2019-09-08,  3000.00
404,  207,  101,  305,  2019-06-21,  1500.00
405,  203,  104,  